version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins
    ports:
      - '8888:8080'
      - '50000:50000'
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    user: root
    restart: always
